CREATE SCHEMA `test` DEFAULT CHARACTER SET utf8mb4 ;
CREATE TABLE `test`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(25) NOT NULL,
  `USER_AGE` INT NOT NULL,
  `USER_IS_ADMIN` BIT NOT NULL,
  `USER_CREATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`));
